language: node_js
node_js:
  - 8
sudo: false
cache: yarn
before_deploy:
  - yarn build
deploy:
  provider: firebase
  token:
    secure: BNB6CcNZJET3dZDwYeIdB9Lpe9iNEpAR8S0h55WdIaoKiV5UHphX/EGwVx/eYYSoqt2+oc66WLb5IGzYlVpNb4enFXnGPPfCdvXVuRTRhOFmK1lctcQ46QZaYYmVZHMns3LlsI74tGd4OdjVEfnb2cwx+vXP6TocVjNTkYyv8ZT3SoPRtrD+zgS363zdtOpNEViVXjToicfkx0I/8qcnBrHgoqSc0iqNmcp7oqAh05ISotXLO8Wp34ofqULW85Ld/eESAIjJYhTNN2cGR4yzyP9GHOFUd9qcmo1RD6Sf9Hq4ta4dE8BClrt7OaCDizAR9v5cmyM8JeU9QZwhsPj5G7FEvJmjOwt2T+lro8e0OdnJ7I0QdbTsm9MVdUH3gaEKZIE1rHJJ+PV3ymKojyZQs7Rl5HO91n/dSFstezPtBxzpd06xgApGL0tBwxG9b46DVQ+IIzkFxP58w3tQPlxL6XNm5QfhK9jIvx6D0dneFvb3309lHVdGPs4sMHgic2Ql/k9jSIZxaz44KGQoojH/2BbWN5wCo+uj/VaN4uwV5jH1dyKGLR9Mk4ke84zScUpJRJCS4l/g6JpGNDkn4PnJtYIA7qBFnESWF91dw1zuyMFPzGYjqxaBQh5rKUgVPMMO/haJDdB2q7rbO3l5KXSw0hAATEoG4eYhv7koRl/dFDc=
  skip_cleanup: true
notifications:
  slack:
    secure: 'sobesfeLL98s7gKL20Ddx94JKsx6pePEracgplpCgVkGNSQnyzxU3QQr0g0bP4/hVSkwwdWrx7p/RGJAvqIZNXfke2Vs+JUMOijfR2HUMJo8ZH8EJN4nPmMkMFgK/Zylb1npEBgNlWIhVcTIjOsBLi4lVs4UjPirBpD979QbkR1XutOcpOY/lf9yYf7GgyZoAuqINL3wNQ4rufE0KF2D1btstDhn2Bh6Q/0Fhg/3pyX1yAATY9V1qEuj21Ai+5iBnRjiS5OEENN9u3/chbfg4UomHy8P2GIhgiFFVwzqGYn62+NAy5ihDW98FmjDai3F86Sust7qF6LyyXF+OA1huqLFuTdb2eMsqnrWC44SuFgCchB5R8zN4XGe1YlgbzI08rl25avhs06f7qCnRwFjP/bPy9LkfFmWJc7QlPJRvAShpnCq0ssXZzCrpxS11CXHP1yYt56WYg3DdSmFAj0EyBSc0HRLKf7dlPBQKCFHt30o4lvSY0RWscaXlZQKi2ER2MqMwhKKl8BQogDeV2mWkUXeZ/CrNJL3124EoHaqhsrVZILMrb+4gt0WFKqweNlu+HMgZXZmrPeVJVCEZ5cA1TKGND/yqdoAhymtPDMR9g9O66UH6PKLimveVhh+E3cIucoRBARv6FPsQ+ON4VsXcxGVU8ubjf+rQ77J29ebUmc='
