language: node_js

node_js:
  - 8

before_deploy:
  - yarn build

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash

script:
  - yarn test

before_deploy:
  - yarn build

deploy:
  provider: surge
  project: ./build/
  domain: wsg.msroed.io
  skip_cleanup: true
